import type { Metadata } from 'next';
import { localizePath, type Locale } from './i18n-routes';

// The live site redirects framaxsolutions.com to www, so www is the canonical host
export const SITE_URL = 'https://www.framaxsolutions.com';
export const SITE_NAME = 'Framax Solutions';

type PageText = { title: string; description: string };

/** Search result title and description for each public page, per language */
const PAGES = {
    home: {
        path: '/',
        en: {
            title: 'Framax Solutions | Software that automates your business',
            description: 'Custom software and automations for small businesses: bookings, invoicing, reminders, CRM and websites. Based in Portugal. Book a free call.',
        },
        pt: {
            title: 'Framax Solutions | Software que automatiza o seu negócio',
            description: 'Software à medida e automações para pequenas empresas: marcações, faturação, lembretes, CRM e websites. Sediados em Portugal. Agende uma chamada gratuita.',
        },
    },
    about: {
        path: '/about',
        en: {
            title: 'How We Work | Framax Solutions',
            description: 'Framax is a software studio in Portugal building websites, management systems and automations for small businesses. See how we work and what we build.',
        },
        pt: {
            title: 'Como Trabalhamos | Framax Solutions',
            description: 'A Framax é um estúdio de software em Portugal que cria websites, sistemas de gestão e automações para pequenas empresas. Veja como trabalhamos e o que criamos.',
        },
    },
    privacy: {
        path: '/legal/privacy',
        en: {
            title: 'Privacy Policy | Framax Solutions',
            description: 'How Framax Solutions collects, uses and protects your personal data.',
        },
        pt: {
            title: 'Política de Privacidade | Framax Solutions',
            description: 'Como a Framax Solutions recolhe, utiliza e protege os seus dados pessoais.',
        },
    },
    terms: {
        path: '/legal/terms',
        en: {
            title: 'Terms of Service | Framax Solutions',
            description: 'The terms that apply when you use the Framax Solutions website and services.',
        },
        pt: {
            title: 'Termos de Serviço | Framax Solutions',
            description: 'Os termos aplicáveis à utilização do website e dos serviços da Framax Solutions.',
        },
    },
} satisfies Record<string, { path: string } & Record<Locale, PageText>>;

export type SeoPage = keyof typeof PAGES;

export const SEO_PAGES = Object.values(PAGES).map((page) => page.path);

/** Absolute URL for a path, without a trailing slash on the homepage (matches the canonical links) */
export function absoluteUrl(path: string): string {
    return path === '/' ? SITE_URL : `${SITE_URL}${path}`;
}

/**
 * Metadata for a public page in one language: title, description, canonical URL,
 * hreflang links pointing Google to the page's other language, and the share image
 * generated by app/opengraph-image.tsx (English) or app/pt/opengraph-image.tsx.
 */
export function pageMetadata(page: SeoPage, locale: Locale): Metadata {
    const { path } = PAGES[page];
    const { title, description } = PAGES[page][locale];
    const url = localizePath(path, locale);
    // Set explicitly: Next.js doesn't pass the generated image down to every nested page
    const image = {
        url: locale === 'pt' ? '/pt/opengraph-image' : '/opengraph-image',
        width: 1200,
        height: 630,
        alt: title,
    };

    return {
        title: { absolute: title },
        description,
        alternates: {
            canonical: url,
            languages: {
                en: path,
                'pt-PT': localizePath(path, 'pt'),
                'x-default': path,
            },
        },
        openGraph: {
            title,
            description,
            url,
            siteName: SITE_NAME,
            locale: locale === 'pt' ? 'pt_PT' : 'en_US',
            alternateLocale: locale === 'pt' ? 'en_US' : 'pt_PT',
            type: 'website',
            images: [image],
        },
        twitter: {
            card: 'summary_large_image',
            title,
            description,
            images: [image.url],
        },
    };
}
